version: "3"
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/app
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: root
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
