version: "3"
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/app
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: root
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
